MOUSEKEY_ENABLE = no    # Mouse keys
RGBLIGHT_ENABLE = no   # Enable WS2812 RGB underlight.
OLED_ENABLE     = yes
LTO_ENABLE      = yes
UNICODE_ENABLE = yes
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
CONSOLE_ENABLE = no
